"""add animal_id to sales

Revision ID: 86593a4508eb
Revises: ea6671982ea9
Create Date: 2025-08-29 04:27:52.930138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86593a4508eb'
down_revision: Union[str, Sequence[str], None] = 'ea6671982ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('product', sa.String(), nullable=False))
    op.add_column('sales', sa.Column('quantity', sa.Float(), nullable=False))
    op.add_column('sales', sa.Column('unit_price', sa.Float(), nullable=False))
    op.add_column('sales', sa.Column('total_amount', sa.Float(), nullable=False))
    op.alter_column('sales', 'animal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('sales', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('price', sa.FLOAT(), nullable=False))
    op.alter_column('sales', 'animal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('sales', 'total_amount')
    op.drop_column('sales', 'unit_price')
    op.drop_column('sales', 'quantity')
    op.drop_column('sales', 'product')
    # ### end Alembic commands ###
